### ISSUE TITLE
CLI Update Tracking Issue

### ISSUE THREAD

**Issue by alexwykoff** [dxos/cli#62]
- [x] CLI tools are all using latest SDK, ECHO, HALO as needed
- [ ] Code coverage exists for all packages in monorepo https://github.com/dxos/cli/issues/54
- [x] Extraneous dependencies are pruned (ex: no jq exec)
- [x] Documentation is updated for all packages in monorepo
